application: issue-1
version: d
runtime: python27
api_version: 1
threadsafe: true

default_expiration: "1m"

handlers:
- url: /favicon.ico
  static_files: html/images/favicon.ico
  upload: html/images/favicon.ico

- url: /css
  static_dir: html/css

- url: /scripts
  static_dir: javascript
  
- url: /images
  static_dir: html/images
  
- url: /
  static_files: html/index.html
  upload: html/index.html
  
- url: /.*
  script: main.app
